#!/usr/bin/bash
echo "== Create Bucket"

if [ $# -eq 0 ]; then
    echo "No Bucket Name Provided"
    exit 1
fi

BUCKET_NAME="$1"
REGION="$2"
aws s3api create-bucket --bucket $BUCKET_NAME --create-bucket-configuration LocationConstraint=$REGION